/**
 * This class is generated by jOOQ
 */
package org.webonise.sql;

/**
 * A class modelling foreign key relationships between tables of the <code>todo_task</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<org.webonise.sql.tables.records.TasksRecord, java.lang.Integer> IDENTITY_TASKS = Identities0.IDENTITY_TASKS;
	public static final org.jooq.Identity<org.webonise.sql.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<org.webonise.sql.tables.records.DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = UniqueKeys0.KEY_DATABASECHANGELOGLOCK_PRIMARY;
	public static final org.jooq.UniqueKey<org.webonise.sql.tables.records.TasksRecord> KEY_TASKS_PRIMARY = UniqueKeys0.KEY_TASKS_PRIMARY;
	public static final org.jooq.UniqueKey<org.webonise.sql.tables.records.UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<org.webonise.sql.tables.records.TasksRecord, java.lang.Integer> IDENTITY_TASKS = createIdentity(org.webonise.sql.tables.Tasks.TASKS, org.webonise.sql.tables.Tasks.TASKS.TASK_ID);
		public static org.jooq.Identity<org.webonise.sql.tables.records.UsersRecord, java.lang.Integer> IDENTITY_USERS = createIdentity(org.webonise.sql.tables.Users.USERS, org.webonise.sql.tables.Users.USERS.USER_ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<org.webonise.sql.tables.records.DatabasechangeloglockRecord> KEY_DATABASECHANGELOGLOCK_PRIMARY = createUniqueKey(org.webonise.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK, org.webonise.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
		public static final org.jooq.UniqueKey<org.webonise.sql.tables.records.TasksRecord> KEY_TASKS_PRIMARY = createUniqueKey(org.webonise.sql.tables.Tasks.TASKS, org.webonise.sql.tables.Tasks.TASKS.TASK_ID);
		public static final org.jooq.UniqueKey<org.webonise.sql.tables.records.UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(org.webonise.sql.tables.Users.USERS, org.webonise.sql.tables.Users.USERS.USER_ID);
	}
}
