/**
 * This class is generated by jOOQ
 */
package org.webonise.sql;

/**
 * Convenience access to all tables in todo_task
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table todo_task.DATABASECHANGELOG
	 */
	public static final org.webonise.sql.tables.Databasechangelog DATABASECHANGELOG = org.webonise.sql.tables.Databasechangelog.DATABASECHANGELOG;

	/**
	 * The table todo_task.DATABASECHANGELOGLOCK
	 */
	public static final org.webonise.sql.tables.Databasechangeloglock DATABASECHANGELOGLOCK = org.webonise.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

	/**
	 * The table todo_task.tasks
	 */
	public static final org.webonise.sql.tables.Tasks TASKS = org.webonise.sql.tables.Tasks.TASKS;

	/**
	 * The table todo_task.users
	 */
	public static final org.webonise.sql.tables.Users USERS = org.webonise.sql.tables.Users.USERS;
}
