/**
 * This class is generated by jOOQ
 */
package org.webonise.sql;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TodoTask extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = -1890241826;

	/**
	 * The reference instance of <code>todo_task</code>
	 */
	public static final TodoTask TODO_TASK = new TodoTask();

	/**
	 * No further instances allowed
	 */
	private TodoTask() {
		super("todo_task");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			org.webonise.sql.tables.Databasechangelog.DATABASECHANGELOG,
			org.webonise.sql.tables.Databasechangeloglock.DATABASECHANGELOGLOCK,
			org.webonise.sql.tables.Tasks.TASKS,
			org.webonise.sql.tables.Users.USERS);
	}
}
