/**
 * This class is generated by jOOQ
 */
package org.webonise.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TasksRecord extends org.jooq.impl.UpdatableRecordImpl<org.webonise.sql.tables.records.TasksRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = -151686688;

	/**
	 * Setter for <code>todo_task.tasks.task_id</code>.
	 */
	public void setTaskId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>todo_task.tasks.task_id</code>.
	 */
	public java.lang.Integer getTaskId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>todo_task.tasks.task_name</code>.
	 */
	public void setTaskName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>todo_task.tasks.task_name</code>.
	 */
	public java.lang.String getTaskName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>todo_task.tasks.is_done</code>.
	 */
	public void setIsDone(java.lang.Boolean value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>todo_task.tasks.is_done</code>.
	 */
	public java.lang.Boolean getIsDone() {
		return (java.lang.Boolean) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return org.webonise.sql.tables.Tasks.TASKS.TASK_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return org.webonise.sql.tables.Tasks.TASKS.TASK_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field3() {
		return org.webonise.sql.tables.Tasks.TASKS.IS_DONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getTaskId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTaskName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value3() {
		return getIsDone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TasksRecord value1(java.lang.Integer value) {
		setTaskId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TasksRecord value2(java.lang.String value) {
		setTaskName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TasksRecord value3(java.lang.Boolean value) {
		setIsDone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TasksRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Boolean value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TasksRecord
	 */
	public TasksRecord() {
		super(org.webonise.sql.tables.Tasks.TASKS);
	}

	/**
	 * Create a detached, initialised TasksRecord
	 */
	public TasksRecord(java.lang.Integer taskId, java.lang.String taskName, java.lang.Boolean isDone) {
		super(org.webonise.sql.tables.Tasks.TASKS);

		setValue(0, taskId);
		setValue(1, taskName);
		setValue(2, isDone);
	}
}
