/**
 * This class is generated by jOOQ
 */
package org.webonise.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangeloglock implements java.io.Serializable {

	private static final long serialVersionUID = 1172095786;

	private java.lang.Integer  id;
	private java.lang.Boolean  locked;
	private java.sql.Timestamp lockgranted;
	private java.lang.String   lockedby;

	public Databasechangeloglock() {}

	public Databasechangeloglock(
		java.lang.Integer  id,
		java.lang.Boolean  locked,
		java.sql.Timestamp lockgranted,
		java.lang.String   lockedby
	) {
		this.id = id;
		this.locked = locked;
		this.lockgranted = lockgranted;
		this.lockedby = lockedby;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Boolean getLocked() {
		return this.locked;
	}

	public void setLocked(java.lang.Boolean locked) {
		this.locked = locked;
	}

	public java.sql.Timestamp getLockgranted() {
		return this.lockgranted;
	}

	public void setLockgranted(java.sql.Timestamp lockgranted) {
		this.lockgranted = lockgranted;
	}

	public java.lang.String getLockedby() {
		return this.lockedby;
	}

	public void setLockedby(java.lang.String lockedby) {
		this.lockedby = lockedby;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Databasechangeloglock other = (Databasechangeloglock) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		}
		else if (!id.equals(other.id))
			return false;
		if (locked == null) {
			if (other.locked != null)
				return false;
		}
		else if (!locked.equals(other.locked))
			return false;
		if (lockgranted == null) {
			if (other.lockgranted != null)
				return false;
		}
		else if (!lockgranted.equals(other.lockgranted))
			return false;
		if (lockedby == null) {
			if (other.lockedby != null)
				return false;
		}
		else if (!lockedby.equals(other.lockedby))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((locked == null) ? 0 : locked.hashCode());
		result = prime * result + ((lockgranted == null) ? 0 : lockgranted.hashCode());
		result = prime * result + ((lockedby == null) ? 0 : lockedby.hashCode());
		return result;
	}
}
