/**
 * This class is generated by jOOQ
 */
package org.webonise.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Databasechangelog implements java.io.Serializable {

	private static final long serialVersionUID = -447601725;

	private java.lang.String   id;
	private java.lang.String   author;
	private java.lang.String   filename;
	private java.sql.Timestamp dateexecuted;
	private java.lang.Integer  orderexecuted;
	private java.lang.String   exectype;
	private java.lang.String   md5sum;
	private java.lang.String   description;
	private java.lang.String   comments;
	private java.lang.String   tag;
	private java.lang.String   liquibase;
	private java.lang.String   contexts;
	private java.lang.String   labels;

	public Databasechangelog() {}

	public Databasechangelog(
		java.lang.String   id,
		java.lang.String   author,
		java.lang.String   filename,
		java.sql.Timestamp dateexecuted,
		java.lang.Integer  orderexecuted,
		java.lang.String   exectype,
		java.lang.String   md5sum,
		java.lang.String   description,
		java.lang.String   comments,
		java.lang.String   tag,
		java.lang.String   liquibase,
		java.lang.String   contexts,
		java.lang.String   labels
	) {
		this.id = id;
		this.author = author;
		this.filename = filename;
		this.dateexecuted = dateexecuted;
		this.orderexecuted = orderexecuted;
		this.exectype = exectype;
		this.md5sum = md5sum;
		this.description = description;
		this.comments = comments;
		this.tag = tag;
		this.liquibase = liquibase;
		this.contexts = contexts;
		this.labels = labels;
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getAuthor() {
		return this.author;
	}

	public void setAuthor(java.lang.String author) {
		this.author = author;
	}

	public java.lang.String getFilename() {
		return this.filename;
	}

	public void setFilename(java.lang.String filename) {
		this.filename = filename;
	}

	public java.sql.Timestamp getDateexecuted() {
		return this.dateexecuted;
	}

	public void setDateexecuted(java.sql.Timestamp dateexecuted) {
		this.dateexecuted = dateexecuted;
	}

	public java.lang.Integer getOrderexecuted() {
		return this.orderexecuted;
	}

	public void setOrderexecuted(java.lang.Integer orderexecuted) {
		this.orderexecuted = orderexecuted;
	}

	public java.lang.String getExectype() {
		return this.exectype;
	}

	public void setExectype(java.lang.String exectype) {
		this.exectype = exectype;
	}

	public java.lang.String getMd5sum() {
		return this.md5sum;
	}

	public void setMd5sum(java.lang.String md5sum) {
		this.md5sum = md5sum;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getComments() {
		return this.comments;
	}

	public void setComments(java.lang.String comments) {
		this.comments = comments;
	}

	public java.lang.String getTag() {
		return this.tag;
	}

	public void setTag(java.lang.String tag) {
		this.tag = tag;
	}

	public java.lang.String getLiquibase() {
		return this.liquibase;
	}

	public void setLiquibase(java.lang.String liquibase) {
		this.liquibase = liquibase;
	}

	public java.lang.String getContexts() {
		return this.contexts;
	}

	public void setContexts(java.lang.String contexts) {
		this.contexts = contexts;
	}

	public java.lang.String getLabels() {
		return this.labels;
	}

	public void setLabels(java.lang.String labels) {
		this.labels = labels;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Databasechangelog other = (Databasechangelog) obj;
		if (id == null) {
			if (other.id != null)
				return false;
		}
		else if (!id.equals(other.id))
			return false;
		if (author == null) {
			if (other.author != null)
				return false;
		}
		else if (!author.equals(other.author))
			return false;
		if (filename == null) {
			if (other.filename != null)
				return false;
		}
		else if (!filename.equals(other.filename))
			return false;
		if (dateexecuted == null) {
			if (other.dateexecuted != null)
				return false;
		}
		else if (!dateexecuted.equals(other.dateexecuted))
			return false;
		if (orderexecuted == null) {
			if (other.orderexecuted != null)
				return false;
		}
		else if (!orderexecuted.equals(other.orderexecuted))
			return false;
		if (exectype == null) {
			if (other.exectype != null)
				return false;
		}
		else if (!exectype.equals(other.exectype))
			return false;
		if (md5sum == null) {
			if (other.md5sum != null)
				return false;
		}
		else if (!md5sum.equals(other.md5sum))
			return false;
		if (description == null) {
			if (other.description != null)
				return false;
		}
		else if (!description.equals(other.description))
			return false;
		if (comments == null) {
			if (other.comments != null)
				return false;
		}
		else if (!comments.equals(other.comments))
			return false;
		if (tag == null) {
			if (other.tag != null)
				return false;
		}
		else if (!tag.equals(other.tag))
			return false;
		if (liquibase == null) {
			if (other.liquibase != null)
				return false;
		}
		else if (!liquibase.equals(other.liquibase))
			return false;
		if (contexts == null) {
			if (other.contexts != null)
				return false;
		}
		else if (!contexts.equals(other.contexts))
			return false;
		if (labels == null) {
			if (other.labels != null)
				return false;
		}
		else if (!labels.equals(other.labels))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((author == null) ? 0 : author.hashCode());
		result = prime * result + ((filename == null) ? 0 : filename.hashCode());
		result = prime * result + ((dateexecuted == null) ? 0 : dateexecuted.hashCode());
		result = prime * result + ((orderexecuted == null) ? 0 : orderexecuted.hashCode());
		result = prime * result + ((exectype == null) ? 0 : exectype.hashCode());
		result = prime * result + ((md5sum == null) ? 0 : md5sum.hashCode());
		result = prime * result + ((description == null) ? 0 : description.hashCode());
		result = prime * result + ((comments == null) ? 0 : comments.hashCode());
		result = prime * result + ((tag == null) ? 0 : tag.hashCode());
		result = prime * result + ((liquibase == null) ? 0 : liquibase.hashCode());
		result = prime * result + ((contexts == null) ? 0 : contexts.hashCode());
		result = prime * result + ((labels == null) ? 0 : labels.hashCode());
		return result;
	}
}
