/**
 * This class is generated by jOOQ
 */
package org.webonise.sql.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tasks implements java.io.Serializable {

	private static final long serialVersionUID = -1246796522;

	private java.lang.Integer taskId;
	private java.lang.String  taskName;
	private java.lang.Boolean isDone;

	public Tasks() {}

	public Tasks(
		java.lang.Integer taskId,
		java.lang.String  taskName,
		java.lang.Boolean isDone
	) {
		this.taskId = taskId;
		this.taskName = taskName;
		this.isDone = isDone;
	}

	public java.lang.Integer getTaskId() {
		return this.taskId;
	}

	public void setTaskId(java.lang.Integer taskId) {
		this.taskId = taskId;
	}

	public java.lang.String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(java.lang.String taskName) {
		this.taskName = taskName;
	}

	public java.lang.Boolean getIsDone() {
		return this.isDone;
	}

	public void setIsDone(java.lang.Boolean isDone) {
		this.isDone = isDone;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		final Tasks other = (Tasks) obj;
		if (taskId == null) {
			if (other.taskId != null)
				return false;
		}
		else if (!taskId.equals(other.taskId))
			return false;
		if (taskName == null) {
			if (other.taskName != null)
				return false;
		}
		else if (!taskName.equals(other.taskName))
			return false;
		if (isDone == null) {
			if (other.isDone != null)
				return false;
		}
		else if (!isDone.equals(other.isDone))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((taskId == null) ? 0 : taskId.hashCode());
		result = prime * result + ((taskName == null) ? 0 : taskName.hashCode());
		result = prime * result + ((isDone == null) ? 0 : isDone.hashCode());
		return result;
	}
}
