/**
 * This class is generated by jOOQ
 */
package org.webonise.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tasks extends org.jooq.impl.TableImpl<org.webonise.sql.tables.records.TasksRecord> {

	private static final long serialVersionUID = -2119087793;

	/**
	 * The reference instance of <code>todo_task.tasks</code>
	 */
	public static final org.webonise.sql.tables.Tasks TASKS = new org.webonise.sql.tables.Tasks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.webonise.sql.tables.records.TasksRecord> getRecordType() {
		return org.webonise.sql.tables.records.TasksRecord.class;
	}

	/**
	 * The column <code>todo_task.tasks.task_id</code>.
	 */
	public final org.jooq.TableField<org.webonise.sql.tables.records.TasksRecord, java.lang.Integer> TASK_ID = createField("task_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>todo_task.tasks.task_name</code>.
	 */
	public final org.jooq.TableField<org.webonise.sql.tables.records.TasksRecord, java.lang.String> TASK_NAME = createField("task_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>todo_task.tasks.is_done</code>.
	 */
	public final org.jooq.TableField<org.webonise.sql.tables.records.TasksRecord, java.lang.Boolean> IS_DONE = createField("is_done", org.jooq.impl.SQLDataType.BIT, this, "");

	/**
	 * Create a <code>todo_task.tasks</code> table reference
	 */
	public Tasks() {
		this("tasks", null);
	}

	/**
	 * Create an aliased <code>todo_task.tasks</code> table reference
	 */
	public Tasks(java.lang.String alias) {
		this(alias, org.webonise.sql.tables.Tasks.TASKS);
	}

	private Tasks(java.lang.String alias, org.jooq.Table<org.webonise.sql.tables.records.TasksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tasks(java.lang.String alias, org.jooq.Table<org.webonise.sql.tables.records.TasksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.webonise.sql.TodoTask.TODO_TASK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.webonise.sql.tables.records.TasksRecord, java.lang.Integer> getIdentity() {
		return org.webonise.sql.Keys.IDENTITY_TASKS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.webonise.sql.tables.records.TasksRecord> getPrimaryKey() {
		return org.webonise.sql.Keys.KEY_TASKS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.webonise.sql.tables.records.TasksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.webonise.sql.tables.records.TasksRecord>>asList(org.webonise.sql.Keys.KEY_TASKS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.webonise.sql.tables.Tasks as(java.lang.String alias) {
		return new org.webonise.sql.tables.Tasks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.webonise.sql.tables.Tasks rename(java.lang.String name) {
		return new org.webonise.sql.tables.Tasks(name, null);
	}
}
