/**
 * This class is generated by jOOQ
 */
package org.webonise.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Users extends org.jooq.impl.TableImpl<org.webonise.sql.tables.records.UsersRecord> {

	private static final long serialVersionUID = -1002983502;

	/**
	 * The reference instance of <code>todo_task.users</code>
	 */
	public static final org.webonise.sql.tables.Users USERS = new org.webonise.sql.tables.Users();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<org.webonise.sql.tables.records.UsersRecord> getRecordType() {
		return org.webonise.sql.tables.records.UsersRecord.class;
	}

	/**
	 * The column <code>todo_task.users.user_id</code>.
	 */
	public final org.jooq.TableField<org.webonise.sql.tables.records.UsersRecord, java.lang.Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>todo_task.users.user_name</code>.
	 */
	public final org.jooq.TableField<org.webonise.sql.tables.records.UsersRecord, java.lang.String> USER_NAME = createField("user_name", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>todo_task.users.password</code>.
	 */
	public final org.jooq.TableField<org.webonise.sql.tables.records.UsersRecord, java.lang.String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>todo_task.users</code> table reference
	 */
	public Users() {
		this("users", null);
	}

	/**
	 * Create an aliased <code>todo_task.users</code> table reference
	 */
	public Users(java.lang.String alias) {
		this(alias, org.webonise.sql.tables.Users.USERS);
	}

	private Users(java.lang.String alias, org.jooq.Table<org.webonise.sql.tables.records.UsersRecord> aliased) {
		this(alias, aliased, null);
	}

	private Users(java.lang.String alias, org.jooq.Table<org.webonise.sql.tables.records.UsersRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, org.webonise.sql.TodoTask.TODO_TASK, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<org.webonise.sql.tables.records.UsersRecord, java.lang.Integer> getIdentity() {
		return org.webonise.sql.Keys.IDENTITY_USERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<org.webonise.sql.tables.records.UsersRecord> getPrimaryKey() {
		return org.webonise.sql.Keys.KEY_USERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<org.webonise.sql.tables.records.UsersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<org.webonise.sql.tables.records.UsersRecord>>asList(org.webonise.sql.Keys.KEY_USERS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.webonise.sql.tables.Users as(java.lang.String alias) {
		return new org.webonise.sql.tables.Users(alias, this);
	}

	/**
	 * Rename this table
	 */
	public org.webonise.sql.tables.Users rename(java.lang.String name) {
		return new org.webonise.sql.tables.Users(name, null);
	}
}
